language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --features "random-all"
  - cargo test --verbose --features "random-all"